# Site settings
title: Welcome to my Profile
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Welcome
user_description: During my studies I worked for 3 years in a large company in the field of Business Intelligence. In my master's degree I focused on the topics Machine Learning and Blockchain, which I applied in my final theses. Furthermore, in cooperation with a start-up company, an Android app was developed. It was connected to a Rasberry Pi via Bluetooth, which was attached to motion sensors at the same time to classify the wearer's movement using machine learning. The use case was a sports app that could monitor whether you were doing exercises correctly.
user_title: I am Jerinas Gresch - BI Analyst & Software Developer
email: anon@anon.com
twitter_username:
github_username: 
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
